<a href="https://colab.research.google.com/github/PrachiKumar298/MLLab/blob/main/MLLab7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Iris

In [ ]:
from sklearn.datasets import load_iris

iris = load_iris()
X = iris.data
y = iris.target

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

X_train shape: (105, 4)
X_test shape: (45, 4)
y_train shape: (105,)
y_test shape: (45,)

In [ ]:
import pandas as pd
import numpy as np


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import StackingClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

In [ ]:
bagging_model = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=100,
    random_state=42
)

In [ ]:
adaboost_model = AdaBoostClassifier(
    estimator=DecisionTreeClassifier(max_depth=1),
    n_estimators=100,
    learning_rate=0.5,
    random_state=42
)

adaboost_model.fit(X_train, y_train)
y_pred_adaboost = adaboost_model.predict(X_test)

gboost_model = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)
gboost_model.fit(X_train, y_train)
y_pred_gboost = gboost_model.predict(X_test)

In [ ]:
base_learners = [
    ('dt', DecisionTreeClassifier()),
    ('knn', KNeighborsClassifier()),
    ('lr', LogisticRegression(max_iter=1000))
]

stacking_model = StackingClassifier(
    estimators=base_learners,
    final_estimator=LogisticRegression(),
    cv=5
)

In [ ]:
print('AdaBoost Classifier Evaluation:')
print(f'Accuracy: {accuracy_score(y_test, y_pred_adaboost):.4f}')
print(f'Precision: {precision_score(y_test, y_pred_adaboost, average="weighted"):.4f}')
print(f'Recall: {recall_score(y_test, y_pred_adaboost, average="weighted"):.4f}')
print(f'F1-score: {f1_score(y_test, y_pred_adaboost, average="weighted"):.4f}')
print('\nClassification Report:')
print(classification_report(y_test, y_pred_adaboost))
print('\nConfusion Matrix:')
print(confusion_matrix(y_test, y_pred_adaboost))

AdaBoost Classifier Evaluation:
Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1-score: 1.0000

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45


Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

In [ ]:
print('Gradient Boosting Classifier Evaluation:')
print(f'Accuracy: {accuracy_score(y_test, y_pred_gboost):.4f}')
print(f'Precision: {precision_score(y_test, y_pred_gboost, average="weighted"):.4f}')
print(f'Recall: {recall_score(y_test, y_pred_gboost, average="weighted"):.4f}')
print(f'F1-score: {f1_score(y_test, y_pred_gboost, average="weighted"):.4f}')
print('\nClassification Report:')
print(classification_report(y_test, y_pred_gboost))
print('\nConfusion Matrix:')
print(confusion_matrix(y_test, y_pred_gboost))

Gradient Boosting Classifier Evaluation:
Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1-score: 1.0000

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45


Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

In [ ]:
bagging_model.fit(X_train, y_train)
y_pred_bagging = bagging_model.predict(X_test)

print('Bagging Classifier Evaluation:')
print(f'Accuracy: {accuracy_score(y_test, y_pred_bagging):.4f}')
print(f'Precision: {precision_score(y_test, y_pred_bagging, average="weighted"):.4f}')
print(f'Recall: {recall_score(y_test, y_pred_bagging, average="weighted"):.4f}')
print(f'F1-score: {f1_score(y_test, y_pred_bagging, average="weighted"):.4f}')
print('\nClassification Report:')
print(classification_report(y_test, y_pred_bagging))
print('\nConfusion Matrix:')
print(confusion_matrix(y_test, y_pred_bagging))

Bagging Classifier Evaluation:
Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1-score: 1.0000

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45


Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

In [ ]:
stacking_model.fit(X_train, y_train)
y_pred_stacking = stacking_model.predict(X_test)

print('Stacking Classifier Evaluation:')
print(f'Accuracy: {accuracy_score(y_test, y_pred_stacking):.4f}')
print(f'Precision: {precision_score(y_test, y_pred_stacking, average="weighted"):.4f}')
print(f'Recall: {recall_score(y_test, y_pred_stacking, average="weighted"):.4f}')
print(f'F1-score: {f1_score(y_test, y_pred_stacking, average="weighted"):.4f}')
print('\nClassification Report:')
print(classification_report(y_test, y_pred_stacking))
print('\nConfusion Matrix:')
print(confusion_matrix(y_test, y_pred_stacking))

Stacking Classifier Evaluation:
Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1-score: 1.0000

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45


Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

Breast Cancer

In [ ]:
from sklearn.datasets import load_breast_cancer

breast_cancer = load_breast_cancer()
X_bc = breast_cancer.data
y_bc = breast_cancer.target

print(f"Features shape (X_bc): {X_bc.shape}")
print(f"Target shape (y_bc): {y_bc.shape}")

Features shape (X_bc): (569, 30)
Target shape (y_bc): (569,)

In [ ]:
X_train_bc, X_test_bc, y_train_bc, y_test_bc = train_test_split(X_bc, y_bc, test_size=0.3, random_state=42)

print(f"X_train_bc shape: {X_train_bc.shape}")
print(f"X_test_bc shape: {X_test_bc.shape}")
print(f"y_train_bc shape: {y_train_bc.shape}")
print(f"y_test_bc shape: {y_test_bc.shape}")

X_train_bc shape: (398, 30)
X_test_bc shape: (171, 30)
y_train_bc shape: (398,)
y_test_bc shape: (171,)

In [ ]:
bagging_model_bc = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=100,
    random_state=42
)
bagging_model_bc.fit(X_train_bc, y_train_bc)
y_pred_bagging_bc = bagging_model_bc.predict(X_test_bc)

print('Bagging Classifier Evaluation (Breast Cancer Dataset):')
print(f'Accuracy: {accuracy_score(y_test_bc, y_pred_bagging_bc):.4f}')
print(f'Precision: {precision_score(y_test_bc, y_pred_bagging_bc, average="weighted"):.4f}')
print(f'Recall: {recall_score(y_test_bc, y_pred_bagging_bc, average="weighted"):.4f}')
print(f'F1-score: {f1_score(y_test_bc, y_pred_bagging_bc, average="weighted"):.4f}')
print('\nClassification Report:')
print(classification_report(y_test_bc, y_pred_bagging_bc))
print('\nConfusion Matrix:')
print(confusion_matrix(y_test_bc, y_pred_bagging_bc))

Bagging Classifier Evaluation (Breast Cancer Dataset):
Accuracy: 0.9591
Precision: 0.9590
Recall: 0.9591
F1-score: 0.9590

Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.94      0.94        63
           1       0.96      0.97      0.97       108

    accuracy                           0.96       171
   macro avg       0.96      0.95      0.96       171
weighted avg       0.96      0.96      0.96       171


Confusion Matrix:
[[ 59   4]
 [  3 105]]

In [ ]:
adaboost_model_bc = AdaBoostClassifier(
    estimator=DecisionTreeClassifier(max_depth=1),
    n_estimators=100,
    learning_rate=0.5,
    random_state=42
)
adaboost_model_bc.fit(X_train_bc, y_train_bc)
y_pred_adaboost_bc = adaboost_model_bc.predict(X_test_bc)

gboost_model_bc = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)
gboost_model_bc.fit(X_train_bc, y_train_bc)
y_pred_gboost_bc = gboost_model_bc.predict(X_test_bc)

print('AdaBoost Classifier Evaluation (Breast Cancer Dataset):')
print(f'Accuracy: {accuracy_score(y_test_bc, y_pred_adaboost_bc):.4f}')
print(f'Precision: {precision_score(y_test_bc, y_pred_adaboost_bc, average="weighted"):.4f}')
print(f'Recall: {recall_score(y_test_bc, y_pred_adaboost_bc, average="weighted"):.4f}')
print(f'F1-score: {f1_score(y_test_bc, y_pred_adaboost_bc, average="weighted"):.4f}')
print('\nClassification Report:')
print(classification_report(y_test_bc, y_pred_adaboost_bc))
print('\nConfusion Matrix:')
print(confusion_matrix(y_test_bc, y_pred_adaboost_bc))

print('\n' + '='*50 + '\n')

print('Gradient Boosting Classifier Evaluation (Breast Cancer Dataset):')
print(f'Accuracy: {accuracy_score(y_test_bc, y_pred_gboost_bc):.4f}')
print(f'Precision: {precision_score(y_test_bc, y_pred_gboost_bc, average="weighted"):.4f}')
print(f'Recall: {recall_score(y_test_bc, y_pred_gboost_bc, average="weighted"):.4f}')
print(f'F1-score: {f1_score(y_test_bc, y_pred_gboost_bc, average="weighted"):.4f}')
print('\nClassification Report:')
print(classification_report(y_test_bc, y_pred_gboost_bc))
print('\nConfusion Matrix:')
print(confusion_matrix(y_test_bc, y_pred_gboost_bc))

AdaBoost Classifier Evaluation (Breast Cancer Dataset):
Accuracy: 0.9649
Precision: 0.9654
Recall: 0.9649
F1-score: 0.9650

Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.97      0.95        63
           1       0.98      0.96      0.97       108

    accuracy                           0.96       171
   macro avg       0.96      0.97      0.96       171
weighted avg       0.97      0.96      0.97       171


Confusion Matrix:
[[ 61   2]
 [  4 104]]

==================================================

Gradient Boosting Classifier Evaluation (Breast Cancer Dataset):
Accuracy: 0.9591
Precision: 0.9590
Recall: 0.9591
F1-score: 0.9590

Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.94      0.94        63
           1       0.96      0.97      0.97       108

    accuracy                           0.96       171
   macro avg       0.96      0.95      0.96       171
weighted avg       0.96      0.96      0.96       171


Confusion Matrix:
[[ 59   4]
 [  3 105]]

In [ ]:
base_learners_bc = [
    ('dt', DecisionTreeClassifier()),
    ('knn', KNeighborsClassifier()),
    ('lr', LogisticRegression(max_iter=1000))
]

stacking_model_bc = StackingClassifier(
    estimators=base_learners_bc,
    final_estimator=LogisticRegression(max_iter=1000),
    cv=5
)
stacking_model_bc.fit(X_train_bc, y_train_bc)
y_pred_stacking_bc = stacking_model_bc.predict(X_test_bc)

print('Stacking Classifier Evaluation (Breast Cancer Dataset):')
print(f'Accuracy: {accuracy_score(y_test_bc, y_pred_stacking_bc):.4f}')
print(f'Precision: {precision_score(y_test_bc, y_pred_stacking_bc, average="weighted"):.4f}')
print(f'Recall: {recall_score(y_test_bc, y_pred_stacking_bc, average="weighted"):.4f}')
print(f'F1-score: {f1_score(y_test_bc, y_pred_stacking_bc, average="weighted"):.4f}')
print('\nClassification Report:')
print(classification_report(y_test_bc, y_pred_stacking_bc))
print('\nConfusion Matrix:')
print(confusion_matrix(y_test_bc, y_pred_stacking_bc))

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Stacking Classifier Evaluation (Breast Cancer Dataset):
Accuracy: 0.9766
Precision: 0.9766
Recall: 0.9766
F1-score: 0.9766

Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.97      0.97        63
           1       0.98      0.98      0.98       108

    accuracy                           0.98       171
   macro avg       0.97      0.97      0.97       171
weighted avg       0.98      0.98      0.98       171


Confusion Matrix:
[[ 61   2]
 [  2 106]]

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

CRISPR

In [ ]:
import pandas as pd

df_crispr = pd.read_csv('/content/crispr_dataset.csv')

print('Crispr Dataset Info:')
df_crispr.info()
print('\nFirst 5 rows of Crispr Dataset:')
display(df_crispr.head())

Crispr Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 882 entries, 0 to 881
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   gRNA        882 non-null    object
 1   efficiency  882 non-null    float64
dtypes: float64(1), object(1)
memory usage: 13.9+ KB

First 5 rows of Crispr Dataset:

                   gRNA  efficiency
0  AAAAACGTACAGGCCCCTGT   -0.323473
1  AAAACGTACAGGCCCCTGTC    1.038653
2  AAACGTACAGGCCCCTGTCA    1.764298
3  AACACGCTGAAACCCGATTC   -0.893392
4  AACCTCAATGTGACGGGCTA    0.132572

In [ ]:
def count_nucleotides(sequence):
    return {
        'A_count': sequence.count('A'),
        'C_count': sequence.count('C'),
        'G_count': sequence.count('G'),
        'T_count': sequence.count('T')
    }

nucleotide_features = df_crispr['gRNA'].apply(count_nucleotides).apply(pd.Series)
df_crispr_processed = pd.concat([df_crispr, nucleotide_features], axis=1)

X_crispr = df_crispr_processed[['A_count', 'C_count', 'G_count', 'T_count']]
y_crispr = df_crispr_processed['efficiency']

X_train_crispr, X_test_crispr, y_train_crispr, y_test_crispr = train_test_split(X_crispr, y_crispr, test_size=0.3, random_state=42)

print(f"X_train_crispr shape: {X_train_crispr.shape}")
print(f"X_test_crispr shape: {X_test_crispr.shape}")
print(f"y_train_crispr shape: {y_train_crispr.shape}")
print(f"y_test_crispr shape: {y_test_crispr.shape}")

display(X_crispr.head())

X_train_crispr shape: (617, 4)
X_test_crispr shape: (265, 4)
y_train_crispr shape: (617,)
y_test_crispr shape: (265,)

   A_count  C_count  G_count  T_count
0        7        6        4        3
1        6        7        4        3
2        6        7        4        3
3        7        7        3        3
4        6        5        5        4

In [ ]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor

from sklearn.ensemble import BaggingRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import StackingRegressor

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print("--- Bagging Regressor ---")
bagging_model_crispr = BaggingRegressor(
    estimator=DecisionTreeRegressor(),
    n_estimators=100,
    random_state=42
)
bagging_model_crispr.fit(X_train_crispr, y_train_crispr)
y_pred_bagging_crispr = bagging_model_crispr.predict(X_test_crispr)

print(f'MAE: {mean_absolute_error(y_test_crispr, y_pred_bagging_crispr):.4f}')
print(f'MSE: {mean_squared_error(y_test_crispr, y_pred_bagging_crispr):.4f}')
print(f'R2 Score: {r2_score(y_test_crispr, y_pred_bagging_crispr):.4f}')

print("\n--- AdaBoost Regressor ---")
adaboost_model_crispr = AdaBoostRegressor(
    estimator=DecisionTreeRegressor(max_depth=4),
    n_estimators=100,
    learning_rate=0.5,
    random_state=42
)
adaboost_model_crispr.fit(X_train_crispr, y_train_crispr)
y_pred_adaboost_crispr = adaboost_model_crispr.predict(X_test_crispr)

print(f'MAE: {mean_absolute_error(y_test_crispr, y_pred_adaboost_crispr):.4f}')
print(f'MSE: {mean_squared_error(y_test_crispr, y_pred_adaboost_crispr):.4f}')
print(f'R2 Score: {r2_score(y_test_crispr, y_pred_adaboost_crispr):.4f}')

print("\n--- Gradient Boosting Regressor ---")
gboost_model_crispr = GradientBoostingRegressor(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)
gboost_model_crispr.fit(X_train_crispr, y_train_crispr)
y_pred_gboost_crispr = gboost_model_crispr.predict(X_test_crispr)

print(f'MAE: {mean_absolute_error(y_test_crispr, y_pred_gboost_crispr):.4f}')
print(f'MSE: {mean_squared_error(y_test_crispr, y_pred_gboost_crispr):.4f}')
print(f'R2 Score: {r2_score(y_test_crispr, y_pred_gboost_crispr):.4f}')

print("\n--- Stacking Regressor ---")
base_learners_crispr = [
    ('dt', DecisionTreeRegressor()),
    ('knn', KNeighborsRegressor()),
    ('lr', LinearRegression())
]

stacking_model_crispr = StackingRegressor(
    estimators=base_learners_crispr,
    final_estimator=LinearRegression(),
    cv=5
)
stacking_model_crispr.fit(X_train_crispr, y_train_crispr)
y_pred_stacking_crispr = stacking_model_crispr.predict(X_test_crispr)

print(f'MAE: {mean_absolute_error(y_test_crispr, y_pred_stacking_crispr):.4f}')
print(f'MSE: {mean_squared_error(y_test_crispr, y_pred_stacking_crispr):.4f}')
print(f'R2 Score: {r2_score(y_test_crispr, y_pred_stacking_crispr):.4f}')

--- Bagging Regressor ---
MAE: 0.9476
MSE: 1.3744
R2 Score: -0.1316

--- AdaBoost Regressor ---
MAE: 0.9088
MSE: 1.2242
R2 Score: -0.0080

--- Gradient Boosting Regressor ---
MAE: 0.8848
MSE: 1.2097
R2 Score: 0.0040

--- Stacking Regressor ---
MAE: 0.8492
MSE: 1.1187
R2 Score: 0.0789